version: '3'
services:
  db:
    image: postgres:16-bullseye
    ports:
      - 5442:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: demopass
      POSTGRES_DB: auth_demo
  test-db:
    image: postgres:16-bullseye
    ports:
      - 5444:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: demopass
      POSTGRES_DB: auth_demo
